[package]
name = "Acordion"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon= "1.8"
criterion= "0.3"
log = "0.4.21"
env_logger = "0.11.3"
neuroflow = "0.2.0"

[[bench]]
name = "fn_benches"
harness = false

[profile.release]
overflow-checks = true
